### ISSUE TITLE
Support for GitHub Enterprise

### ISSUE THREAD

**Issue by billimek** [itsdalmo/github-pr-resource#17]
As a consumer of this resource, I would like to leverage it in conjunction with GitHub Enterprise so that I can take advantage of these new features for things that aren't only in github.com.

For example, [this](https://github.com/itsdalmo/github-pr-resource/blob/master/src/git/git.go#L55) has github.com hardcoded.  We should consider allowing people to reference their own github endpoint as part of the resource configuration.

**Comment by itsdalmo** [comment]
Great idea! Unfortunately I don't have a Github enterprise available to test against, but I'd be happy to make a PR to parameterise it and hopefully get someone to validate that it works.

I'm assuming it should behave just like regular Github, except that it's reachable at a different endpoint, but I might be wrong? Also, since we are using the V4 API, is this something that is/has been available on enterprise for long?

**Comment by itsdalmo** [comment]
According to these:
- https://developer.github.com/enterprise/2.12/v3/#root-endpoint
- https://developer.github.com/enterprise/2.12/v4/guides/forming-calls/#the-graphql-endpoint

And what I could see from their deployment guide for Github Enterprise, it seems like Github enterprise    will most likely live on a single host, which means we only need to take one `endpoint` variable from the user and should possibly be able to do `path.Join()` to get the three endpoints we need.

Assuming the user supplied `endpoint`: `https://example.com`:

- Clone should use `https://<token>@example.com/user/test-repository.git`
- V3 API calls: `https://example.com/api/v3`
- V4 API calls: `https://example.com/api/graphql`

Unfortunately, I can't verify this myself. Do you have an enterprise GH to check against @billimek?

**Comment by devorbitus** [comment]
I work with @billimek and we would be happy to test this against our GHE.

**Comment by itsdalmo** [comment]
Great @billimek! 

So far I think I've gathered that we can just retrieve the URL needed to clone the repository when calling the other API's, so we just need the endpoints for the V3 and V4 API's. For regular Github these can be reached at:

- `https://api.github.com/` for V3
- `https://api.github.com/graphql` for V4

Could you check whether this is the case for your GHE also?

**Comment by billimek** [comment]
This is what the endpoints look like for our GHE:

* `https://github.ourdomain.com/api/v3/` for V3
* `https://github.ourdomain.com/api/graphql`for V4

**Comment by itsdalmo** [comment]
Thanks! I've added two new parameters: `v3_endpoint` and `v4_endpoint`. I made the choice to go with two because Github itself does not follow the `/api/<type>` pattern, so I figured other installations of GHE might not either. 

Since we need to test it, I've added a [new docker tag](https://hub.docker.com/r/itsdalmo/github-pr-resource/tags/) `dev` which is built from master branch. Be great if you could try it out and report back 👍

**Comment by itsdalmo** [comment]
@billimek and @devorbitus - Have you had a chance to test this out? I've released a new version which includes the endpoints, so you can use `latest` or `v0.4.0` if you want.

**Comment by itsdalmo** [comment]
@billimek - Did you have a chance to test this yet?

**Comment by billimek** [comment]
Yes, sorry for the delay. One of our engineers successfully tested this today and I’m planning on doing one final test tomorrow and was going to close out this afterwards.
